#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup-dev-droplet.sh
#
# Bootstrap a fresh Ubuntu 24.04 Droplet for the MyBlock dev environment.
#
# Run as root (or with sudo) on a brand-new Droplet:
#   curl -fsSL https://raw.githubusercontent.com/.../setup-dev-droplet.sh | bash
#   -- or --
#   bash setup-dev-droplet.sh
#
# Before running, set these environment variables or be prompted for them:
#   DO_ACCESS_TOKEN   — DigitalOcean API token (for DOCR login)
#   REGISTRY_NAME     — DOCR registry name (e.g. "myblock")
#   MONGODB_URI       — DO Managed MongoDB connection string
#   JWT_SECRET        — JWT signing secret
#   JWT_REFRESH_SECRET — JWT refresh signing secret
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Helpers ──────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
require() { command -v "$1" &>/dev/null || { error "Required command not found: $1"; exit 1; }; }

# ── Prompt for secrets if not set ────────────────────────
prompt_secret() {
  local var_name="$1"
  local prompt_text="$2"
  if [ -z "${!var_name:-}" ]; then
    read -rsp "${prompt_text}: " value
    echo
    export "$var_name"="$value"
  fi
}

prompt_secret DO_ACCESS_TOKEN   "DigitalOcean API token"
prompt_secret REGISTRY_NAME     "DOCR registry name (e.g. myblock)"
prompt_secret MONGODB_URI       "MongoDB connection string"
prompt_secret JWT_SECRET        "JWT secret"
prompt_secret JWT_REFRESH_SECRET "JWT refresh secret"

# Optional — leave empty if not configured
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-}"
FIREBASE_CLIENT_EMAIL="${FIREBASE_CLIENT_EMAIL:-}"
FIREBASE_PRIVATE_KEY="${FIREBASE_PRIVATE_KEY:-}"
RESEND_API_KEY="${RESEND_API_KEY:-}"

# ── 1. System packages ────────────────────────────────────
info "Updating package index..."
apt-get update -qq

info "Installing prerequisites..."
apt-get install -y -qq \
  ca-certificates \
  curl \
  gnupg \
  lsb-release \
  ufw \
  unzip \
  jq

# ── 2. Docker (official repo, not snap) ──────────────────
if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  systemctl enable --now docker
  info "Docker installed: $(docker --version)"
else
  info "Docker already installed: $(docker --version)"
fi

# ── 3. doctl (DO CLI for registry auth) ──────────────────
if ! command -v doctl &>/dev/null; then
  info "Installing doctl..."
  DOCTL_VERSION=$(curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest \
    | jq -r '.tag_name' | sed 's/v//')
  curl -fsSL "https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz" \
    | tar -xz -C /usr/local/bin
  info "doctl installed: $(doctl version)"
else
  info "doctl already installed: $(doctl version)"
fi

# ── 4. Certbot (Let's Encrypt) ────────────────────────────
if ! command -v certbot &>/dev/null; then
  info "Installing certbot..."
  apt-get install -y -qq certbot python3-certbot-nginx
  info "certbot installed: $(certbot --version)"
else
  info "certbot already installed: $(certbot --version)"
fi

# ── 5. Firewall ───────────────────────────────────────────
info "Configuring UFW firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp    # HTTP (certbot + redirect to HTTPS)
ufw allow 443/tcp   # HTTPS
ufw --force enable
info "UFW status:"
ufw status verbose

# ── 6. App directory structure ────────────────────────────
APP_DIR="/opt/myblock"
info "Creating app directories at ${APP_DIR}..."
mkdir -p "${APP_DIR}/nginx"

# ── 7. Write .env file ────────────────────────────────────
info "Writing .env file..."
# This file is read by docker compose --env-file .env
# It is NOT committed to git — it lives only on the Droplet.
cat > "${APP_DIR}/.env" <<EOF
# Generated by setup-dev-droplet.sh — do not commit
MONGODB_URI=${MONGODB_URI}
REDIS_URL=redis://redis:6379
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
RESEND_API_KEY=${RESEND_API_KEY}
EOF
chmod 600 "${APP_DIR}/.env"
info ".env written (permissions: 600)"

# ── 8. Copy docker-compose and nginx config ───────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"

info "Copying docker-compose.dev.yml..."
cp "${REPO_ROOT}/docker-compose.dev.yml" "${APP_DIR}/docker-compose.dev.yml"

info "Copying nginx/proxy.conf..."
cp "${REPO_ROOT}/nginx/proxy.conf" "${APP_DIR}/nginx/proxy.conf"

# ── 9. Certbot webroot directory ──────────────────────────
mkdir -p /var/www/certbot

# ── 10. DOCR login ────────────────────────────────────────
info "Authenticating doctl with DigitalOcean..."
doctl auth init --access-token "${DO_ACCESS_TOKEN}"

info "Logging in to DO Container Registry (${REGISTRY_NAME})..."
doctl registry login

# ── 11. Pull images ───────────────────────────────────────
# The deploy workflow passes IMAGE_API and IMAGE_ADMIN as env vars.
# On first bootstrap we pull the latest branch tags if they exist.
REGISTRY="registry.digitalocean.com/${REGISTRY_NAME}"

info "Pulling latest API image (develop branch tag)..."
docker pull "${REGISTRY}/myblock-api:develop" || warn "No develop tag yet — skipping API pull."

info "Pulling latest Admin image (develop branch tag)..."
docker pull "${REGISTRY}/myblock-admin:develop" || warn "No develop tag yet — skipping Admin pull."

# ── 12. Start services (without SSL yet) ─────────────────
# Start nginx on HTTP only so certbot can complete the ACME challenge.
# After certs are issued, nginx will serve HTTPS using the mounted certs.
info "Starting services..."
cd "${APP_DIR}"
IMAGE_API="${REGISTRY}/myblock-api:develop" \
IMAGE_ADMIN="${REGISTRY}/myblock-admin:develop" \
docker compose --env-file .env -f docker-compose.dev.yml up -d

# Give containers a moment to start before certbot runs
sleep 5

# ── 13. SSL certificates (Let's Encrypt) ─────────────────
info "Obtaining SSL certificates..."

# api.my-block.app
if [ ! -d "/etc/letsencrypt/live/api.my-block.app" ]; then
  certbot certonly --webroot \
    -w /var/www/certbot \
    -d api.my-block.app \
    --non-interactive \
    --agree-tos \
    --email ops@my-block.app \
    --no-eff-email
  info "SSL cert issued for api.my-block.app"
else
  info "SSL cert for api.my-block.app already exists — skipping."
fi

# admin.my-block.app
if [ ! -d "/etc/letsencrypt/live/admin.my-block.app" ]; then
  certbot certonly --webroot \
    -w /var/www/certbot \
    -d admin.my-block.app \
    --non-interactive \
    --agree-tos \
    --email ops@my-block.app \
    --no-eff-email
  info "SSL cert issued for admin.my-block.app"
else
  info "SSL cert for admin.my-block.app already exists — skipping."
fi

# ── 14. Reload nginx to pick up certs ────────────────────
info "Reloading nginx to activate HTTPS..."
docker exec myblock-nginx nginx -s reload

# ── 15. Certbot auto-renewal via cron ────────────────────
info "Installing certbot auto-renewal cron..."
# Renew twice daily (standard certbot recommendation).
# After renewal, reload nginx so the new cert is live without downtime.
CRON_JOB="0 0,12 * * * root certbot renew --quiet --deploy-hook 'docker exec myblock-nginx nginx -s reload'"
echo "${CRON_JOB}" > /etc/cron.d/certbot-renew
chmod 644 /etc/cron.d/certbot-renew
info "Cron job installed: /etc/cron.d/certbot-renew"

# ── 16. Final health checks ───────────────────────────────
info "Running health checks..."

API_OK=false
ADMIN_OK=false

for i in $(seq 1 12); do
  if curl -sf --max-time 5 "https://api.my-block.app/health" &>/dev/null; then
    API_OK=true
    break
  fi
  sleep 5
done

for i in $(seq 1 12); do
  if curl -sf --max-time 5 "https://admin.my-block.app/health" &>/dev/null; then
    ADMIN_OK=true
    break
  fi
  sleep 5
done

echo
echo "─────────────────────────────────────────────"
$API_OK   && info "  api.my-block.app   — HEALTHY" \
          || warn "  api.my-block.app   — NOT RESPONDING (check docker logs myblock-api)"
$ADMIN_OK && info "  admin.my-block.app — HEALTHY" \
          || warn "  admin.my-block.app — NOT RESPONDING (check docker logs myblock-admin)"
echo "─────────────────────────────────────────────"
echo
info "Setup complete. App directory: ${APP_DIR}"
info "To tail logs: docker compose -f ${APP_DIR}/docker-compose.dev.yml logs -f"
